import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_PATH = os.getenv("KISAANSIGHT_MODEL_PATH", str(BASE_DIR / "models" / "mobilenet_plant.pth"))
FONT_DIR = BASE_DIR / "assets" / "fonts"
STATIC_DIR = BASE_DIR / "static"

API_BASE_URL = os.getenv("KISAANSIGHT_API_URL", "http://127.0.0.1:8000")

FOLIAGE_MIN_RATIO = 0.06
GRADCAM_ACTIVATION_THRESHOLD = 0.60
SOFTMAX_TEMPERATURE = 1.3
OOD_CONFIDENCE_FLOOR = 0.35

CONFIDENCE_CLARIFICATION_THRESHOLD = 0.85
MARGIN_CLARIFICATION_THRESHOLD = 0.20
KEYWORD_MATCH_WEIGHT = 3

TANK_VOLUME_LITERS = 16
TANKS_PER_ACRE = 6
KANALS_PER_ACRE = 8
COST_PER_UNIT_PKR_MIN = 9.5
COST_PER_UNIT_PKR_MAX = 13.5